/// Feishu MCP Server — MCP protocol layer
///
/// Uses rmcp's `#[tool_router]` / `#[tool_handler]` macros to define
/// 13 MCP tools backed by the Feishu API client.

use std::future::Future;
use std::sync::Arc;

use rmcp::{
    ErrorData as McpError,
    handler::server::tool::{Parameters, ToolRouter},
    model::*,
    serve_server, ServerHandler, tool, tool_handler, tool_router,
    transport::io::stdio,
};

use crate::feishu::client::FeishuClient;
use crate::feishu::error::FeishuError;
use crate::middleware::rate_limit::RateLimiter;

// ============================================================================
// Input types for all 13 tools (with JsonSchema for auto-generated inputSchema)
// ============================================================================

mod types;

// ============================================================================
// FeishuMcpServer — the main MCP server struct
// ============================================================================

/// The MCP server wrapping a Feishu API client.
///
/// Clone is required by rmcp's ToolRouter.
#[derive(Clone)]
pub struct FeishuMcpServer {
    /// Feishu API client (shared via Arc)
    pub feishu_client: Arc<FeishuClient>,
    /// Rate limiter for API calls
    pub rate_limiter: Arc<RateLimiter>,
    /// Tool router auto-generated by `#[tool_router]`
    pub tool_router: ToolRouter<Self>,
}

impl FeishuMcpServer {
    /// Create a new FeishuMcpServer
    pub fn new(feishu_client: Arc<FeishuClient>, rate_limiter: Arc<RateLimiter>) -> Self {
        Self {
            feishu_client,
            rate_limiter,
            tool_router: Self::tool_router(),
        }
    }

    /// Run the server with stdio transport (primary MCP transport)
    pub async fn run_stdio(&self) -> anyhow::Result<()> {
        tracing::info!("Starting MCP server with stdio transport");
        let service = self.clone();
        let io = stdio();
        let running = serve_server(service, io).await?;
        running.waiting().await?;
        Ok(())
    }

    /// Run the server with Streamable HTTP transport
    pub async fn run_http(&self, port: u16) -> anyhow::Result<()> {
        tracing::info!(
            "Starting MCP server with Streamable HTTP transport on port {}",
            port
        );
        // For now, fall back to stdio — HTTP transport will be implemented in a future iteration
        tracing::warn!("HTTP transport not yet fully implemented, falling back to stdio");
        self.run_stdio().await
    }
}

// ============================================================================
// MCP Tool Definitions (13 tools across Documents, Tasks, Messages)
// ============================================================================

use types::*;

#[tool_router]
impl FeishuMcpServer {
    // ========================================================================
    // DOCUMENTS TOOLS (5)
    // ========================================================================

    /// Search documents by query string
    #[tool(
        description = "Search documents in Feishu by query string",
        annotations(title = "Search Documents", read_only_hint = true, idempotent_hint = true)
    )]
    async fn search_documents(
        &self,
        params: Parameters<SearchDocumentsInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "search_documents")?;

        match self
            .feishu_client
            .search_documents(&input.query, input.limit.map(|l| l as i32))
            .await
        {
            Ok(docs) => Ok(json_result(&docs)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Get document by ID
    #[tool(
        description = "Get a Feishu document by its document ID",
        annotations(title = "Get Document", read_only_hint = true, idempotent_hint = true)
    )]
    async fn get_document(
        &self,
        params: Parameters<GetDocumentInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "get_document")?;

        match self.feishu_client.get_document(&input.doc_id).await {
            Ok(doc) => Ok(json_result(&doc)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Create a new document
    #[tool(
        description = "Create a new Feishu document with optional content and parent folder",
        annotations(title = "Create Document")
    )]
    async fn create_document(
        &self,
        params: Parameters<CreateDocumentInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "create_document")?;

        match self
            .feishu_client
            .create_document(
                &input.title,
                input.content.as_deref(),
                input.parent_token.as_deref(),
            )
            .await
        {
            Ok(doc) => Ok(json_result(&doc)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Update document content
    #[tool(
        description = "Update the content of an existing Feishu document",
        annotations(title = "Update Document")
    )]
    async fn update_document(
        &self,
        params: Parameters<UpdateDocumentInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "update_document")?;

        match self
            .feishu_client
            .update_document(&input.doc_id, &input.content)
            .await
        {
            Ok(doc) => Ok(json_result(&doc)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// List documents in a folder
    #[tool(
        description = "List documents in a specified Feishu folder",
        annotations(title = "List Documents", read_only_hint = true, idempotent_hint = true)
    )]
    async fn list_documents(
        &self,
        params: Parameters<ListDocumentsInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "list_documents")?;

        match self
            .feishu_client
            .list_documents(
                Some(&input.folder_token),
                input.page_size.map(|p| p as i32),
            )
            .await
        {
            Ok(docs) => Ok(json_result(&docs)),
            Err(e) => Ok(error_result(e)),
        }
    }

    // ========================================================================
    // TASKS TOOLS (5)
    // ========================================================================

    /// List tasks by goal ID
    #[tool(
        description = "List Feishu tasks associated with a specific goal",
        annotations(title = "List Tasks", read_only_hint = true, idempotent_hint = true)
    )]
    async fn list_tasks(
        &self,
        params: Parameters<ListTasksInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "list_tasks")?;

        match self.feishu_client.list_tasks(Some(&input.goal_id)).await {
            Ok(tasks) => Ok(json_result(&tasks)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Get task by ID
    #[tool(
        description = "Get a Feishu task by its task ID",
        annotations(title = "Get Task", read_only_hint = true, idempotent_hint = true)
    )]
    async fn get_task(
        &self,
        params: Parameters<GetTaskInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "get_task")?;

        match self.feishu_client.get_task(&input.task_id).await {
            Ok(task) => Ok(json_result(&task)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Create a new task
    #[tool(
        description = "Create a new Feishu task under a specific goal",
        annotations(title = "Create Task")
    )]
    async fn create_task(
        &self,
        params: Parameters<CreateTaskInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "create_task")?;

        match self
            .feishu_client
            .create_task(
                &input.title,
                None,
                input.assignee_id.as_deref(),
                input.due_date.as_deref(),
                Some(&input.goal_id),
            )
            .await
        {
            Ok(task) => Ok(json_result(&task)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Update task status
    #[tool(
        description = "Update the status of a Feishu task (todo, in_progress, or done)",
        annotations(title = "Update Task Status", idempotent_hint = true)
    )]
    async fn update_task_status(
        &self,
        params: Parameters<UpdateTaskStatusInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "update_task_status")?;

        use crate::feishu::types::TaskStatus;
        let task_status = match input.status.as_str() {
            "todo" => TaskStatus::Todo,
            "in_progress" => TaskStatus::InProgress,
            "done" => TaskStatus::Done,
            _ => {
                return Ok(error_result_msg(format!(
                    "Invalid status: '{}'. Expected 'todo', 'in_progress', or 'done'",
                    input.status
                )));
            }
        };

        match self
            .feishu_client
            .update_task_status(&input.task_id, task_status)
            .await
        {
            Ok(task) => Ok(json_result(&task)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Complete a task
    #[tool(
        description = "Mark a Feishu task as completed",
        annotations(title = "Complete Task", idempotent_hint = true)
    )]
    async fn complete_task(
        &self,
        params: Parameters<CompleteTaskInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "complete_task")?;

        match self.feishu_client.complete_task(&input.task_id).await {
            Ok(task) => Ok(json_result(&task)),
            Err(e) => Ok(error_result(e)),
        }
    }

    // ========================================================================
    // MESSAGES TOOLS (3)
    // ========================================================================

    /// Send a message to a chat
    #[tool(
        description = "Send a message to a Feishu chat (text by default)",
        annotations(title = "Send Message")
    )]
    async fn send_message(
        &self,
        params: Parameters<SendMessageInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "send_message")?;

        let msg_type = input.msg_type.unwrap_or_else(|| "text".to_string());
        match self
            .feishu_client
            .send_message(&input.chat_id, &input.content, &msg_type)
            .await
        {
            Ok(msg) => Ok(json_result(&msg)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Get messages from a chat
    #[tool(
        description = "Get recent messages from a Feishu chat",
        annotations(title = "Get Messages", read_only_hint = true, idempotent_hint = true)
    )]
    async fn get_messages(
        &self,
        params: Parameters<GetMessagesInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "get_messages")?;

        match self
            .feishu_client
            .get_messages(&input.chat_id, input.limit.map(|l| l as i32))
            .await
        {
            Ok(msgs) => Ok(json_result(&msgs)),
            Err(e) => Ok(error_result(e)),
        }
    }

    /// Search messages
    #[tool(
        description = "Search messages across Feishu chats by query string",
        annotations(title = "Search Messages", read_only_hint = true, idempotent_hint = true)
    )]
    async fn search_messages(
        &self,
        params: Parameters<SearchMessagesInput>,
    ) -> Result<CallToolResult, McpError> {
        let input = params.0;
        rate_limit(&self.rate_limiter, "search_messages")?;

        match self
            .feishu_client
            .search_messages(&input.query, input.chat_id.as_deref())
            .await
        {
            Ok(msgs) => Ok(json_result(&msgs)),
            Err(e) => Ok(error_result(e)),
        }
    }
}

// ============================================================================
// ServerHandler implementation (tool_call + list_tools auto-implemented)
// ============================================================================

#[tool_handler]
impl ServerHandler for FeishuMcpServer {
    /// Override default server info to advertise tool capabilities
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::default(),
            capabilities: ServerCapabilities::builder()
                .enable_tools()
                .build(),
            server_info: Implementation {
                name: "feishu-mcp-server".to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
            },
            instructions: Some(
                "Feishu MCP Server — exposes Feishu APIs (documents, tasks, messages) \
                 as MCP tools for Claude Desktop, Cursor, and other MCP clients."
                    .to_string(),
            ),
        }
    }
}

// ============================================================================
// Helper functions
// ============================================================================

/// Check rate limit for a tool call
fn rate_limit(limiter: &RateLimiter, tool: &str) -> Result<(), McpError> {
    if let Err(e) = limiter.check(tool) {
        return Err(McpError::internal_error(
            format!("Rate limit exceeded: retry after {}s", e.retry_after_secs),
            None,
        ));
    }
    Ok(())
}

/// Convert a serializable object to a JSON CallToolResult
fn json_result<T: serde::Serialize>(value: &T) -> CallToolResult {
    let json = serde_json::to_value(value).unwrap_or_default();
    CallToolResult::success(vec![Content::text(json.to_string())])
}

/// Convert a FeishuError to an error CallToolResult
fn error_result(err: FeishuError) -> CallToolResult {
    CallToolResult::error(vec![Content::text(err.to_string())])
}

/// Create an error CallToolResult from a string message
fn error_result_msg(msg: String) -> CallToolResult {
    CallToolResult::error(vec![Content::text(msg)])
}
